### ISSUE TITLE
Multi-Order Spectra

### ISSUE THREAD

**Issue by mikelum** [samuelyeewl/specmatch-emp#17]
I have a number of (HiRES UV-optical-IR) spectra, downloaded from the Keck Archive, reduced with the makee package, and continuum normalized/Doppler corrected using IRAF. The resulting spectra are in fits "multispec" format, and therefore not readable by specmatch-emp.

I can pretty easily convert the multiple orders into to 1-d flux & wavelength arrays, and pass them to the Spectrum object - thereby working around this little issue.

Two questions, though:
First - Is native multispec support on the to-do list?
Second - Does specmatch-emp make any assumptions about the nature of the spectra it receives? Specifically, in multiple order spectra, orders can overlap, or have gaps in between them, resulting in irregular dispersion, duplicate wavelength-flux pairs, or gaps in the wavelength coverage...

**Comment by samuelyeewl** [comment]
Hi Mike,

I don't think we're planning to support multispec natively, sorry! The
HiresSpectrum object does allow you to pass in multiple order spectra, and
there's a function to flatten it after having shifted each order onto a
rest wavelength scale. In that case, the code averages over overlapping
parts of the order, and will have nan elements where there are gaps.

Hope this answers your questions!

Cheers,
Samuel

**Comment by mikelum** [comment]
Thanks for the update.
I'm not too concerned with merging my spectral orders (pyRAF + scombine FTW!). I think I have that part of things handled.

>  In that case, the code averages over overlapping parts of the order, and will have nan elements where there are gaps

Good to know. Would the nan elements appear in the case where the spectrum is created by two arrays?
 I am seeing a problem when trying to fit parameters after loading a spectrum as an array of wavelengths, plus an array of (normalized) fluxes. Basically, the call to linspace crashes with:
"ValueError: The input contains nan values"
The call from specmatch/match.py is:
 424         # Minimize chi-squared
--> 425         out = lmfit.minimize(self.objective, params, method='nelder')

I'm pretty sure that my arrays didn't contain nans, so would there have been something in the matches which would have resulted in nans?


Here's the full snippet of my code, if you care:
```
# Hack to load spectra that weren't in a "happy" format
myHDU = pyfits.open(specFilename)
wlStart = float(myHDU[0].header['CRVAL1'])*unitMult
wlDisp = float(myHDU[0].header['CDELT1'])*unitMult
numPoints = int(myHDU[0].header['NAXIS1'])

wlVals = np.linspace(wlStart, np.round(wlStart+wlDisp*numPoints, 2), numPoints)
# Flux nans are removed here (replaced by continuum)
flxVals = np.array([flx if is_number(flx) else 1.0 for flx in myHDU[0].data])

fullSpectrum=Spectrum(wlVals, flxVals, name=starName)

plotSpec(fullSpectrum)

mySpectrum = fullSpectrum.cut(rangeMin-20, rangeMax+20)
lib = specmatchemp.library.read_hdf(wavlim=[rangeMin-10, rangeMax+10])

myMatches = SpecMatch(mySpectrum, lib=lib, wavlim=(rangeMin-10, rangeMax+10))
myMatches.shift()

plotMatches(myMatches)

# Note: if the spectra cut size is smaller than the default wavstep, bad things happen.
myMatches.match(wavstep=20.)

plotBestMatch(myMatches)

# Generate best-fit parms - Crash occurs here
myMatches.lincomb()

print('Derived Parameters: ')
print('Teff: {0:.0f}, Radius: {1:.2f}, [Fe/H]: {2:.2f}'.format(
    myMatches.results['Teff'], myMatches.results['radius'], myMatches.results['feh']))
```

**Comment by samuelyeewl** [comment]
Hi Mike,

I haven't encountered this problem before. Did the match stage give the
valid results when you plotted it?

Cheers,
Samuel

**Comment by mikelum** [comment]
As far as I can tell, the match stage does give good results. Here's a sample result from the plot call, immediately prior to the lincomb call (note: I'm not plotting a vertical line for the stellar radius - I'm more interested in LogG, but that's another story...):

![61cygb](https://cloud.githubusercontent.com/assets/460592/20365622/a61909b2-abeb-11e6-864b-85fcce59ecca.png)

**Comment by samuelyeewl** [comment]
I think this is fixed in 4ea2015, same problem that @petigura was facing in issue #22. Let me know if you still run into this problem?

**Comment by mikelum** [comment]
Nope...the lincomb call still crashes with 'nan' values. Since this is really a different issue than this one (multispec support), I'll open a new issue.

**Comment by mikelum** [comment]
I retract the last. I was seeing an issue with range selection (different issue). The lincomb() calls **do** appear to be working now. Thanks!
